#ifdef PHYSIS_OPENCL_KERNEL_MODE

void __PS_opencl_kernel1(
    const long int x,
    const long int y,
    const long int z,
    const long int __PS_g_dim_x,
    const long int __PS_g_dim_y,
    const long int __PS_g_dim_z,
    __global float *__PS_g_buf,
    const long int __PS_g_gridattr)
{
  float v = __PS_g_buf[x + (y *__PS_g_dim_x) + (z * __PS_g_dim_x * __PS_g_dim_y)] * 2;
  __PS_g_buf[x + (y * __PS_g_dim_x) + (z * __PS_g_dim_x * __PS_g_dim_y)] = v;
}

__kernel void __PSStencilRun_kernel1(
    long int __PS_dom_xmin,
    long int __PS_dom_xmax,
    long int __PS_dom_ymin,
    long int __PS_dom_ymax,
    long int __PS_dom_zmin,
    long int __PS_dom_zmax,
    long int __PS_g_dim_x,
    long int __PS_g_dim_y,
    long int __PS_g_dim_z,
    __global float *__PS_g_buf,
    const long int __PS_g_gridattr
)
{
  int y = get_global_id(1);
  int x = get_global_id(0);
  if ((x < __PS_dom_xmin) || (x >= __PS_dom_xmax)|| (y < __PS_dom_ymin) || (y >= __PS_dom_ymax)) 
    return ;
  int z;
  for (z = __PS_dom_zmin; z < __PS_dom_zmax; ++z) {
    __PS_opencl_kernel1(
      x, y, z,
      __PS_g_dim_x, __PS_g_dim_y, __PS_g_dim_z,
      __PS_g_buf, __PS_g_gridattr
      );
  }
}


float plus10(float v){
  return v + 10.0;
}

void __PS_opencl_kernel2(
    const long int x,
    const long int y,
    const long int z,
    const long int __PS_g_dim_x,
    const long int __PS_g_dim_y,
    const long int __PS_g_dim_z,
    __global float *__PS_g_buf,
    const long int __PS_g_gridattr)
{
  float v = __PS_g_buf[x + (y * __PS_g_dim_x) + (z * __PS_g_dim_x * __PS_g_dim_y)];
  v = plus10(v);
  __PS_g_buf[x + (y * __PS_g_dim_x) + (z * __PS_g_dim_x * __PS_g_dim_y)] = v;
}

__kernel void __PSStencilRun_kernel2(
    long int __PS_dom_xmin,
    long int __PS_dom_xmax,
    long int __PS_dom_ymin,
    long int __PS_dom_ymax,
    long int __PS_dom_zmin,
    long int __PS_dom_zmax,
    long int __PS_g_dim_x,
    long int __PS_g_dim_y,
    long int __PS_g_dim_z,
    __global float *__PS_g_buf,
    long int __PS_g_gridattr
)
{
  int y = get_global_id(1);
  int x = get_global_id(0);
  if ((x < __PS_dom_xmin) || (x >= __PS_dom_xmax)|| (y < __PS_dom_ymin) || (y >= __PS_dom_ymax)) 
    return ;
  int z;
  for (z = __PS_dom_zmin; z < __PS_dom_zmax; ++z) {
    __PS_opencl_kernel2(
      x, y, z,
      __PS_g_dim_x, __PS_g_dim_y, __PS_g_dim_z,
      __PS_g_buf, __PS_g_gridattr
      );
  }
}

#else /* PHYSIS_OPENCL_KERNEL_MODE */

#define PHYSIS_OPENCL
#include "physis/physis.h"
#include <math.h>

#define SIZEX 64
#define SIZEY 64
#define SIZEZ 64
#define NDIM  3


struct __PSStencil_kernel1
{
  __PSDomain dom;
  PSGrid3DFloat g;
  int __g_index;
};

struct __PSStencil_kernel2
{
  __PSDomain dom;
  PSGrid3DFloat g;
  int __g_index;
};


void init (float *buff, const int dx, const int dy, const int dz){
    int jx, jy, jz;
    for (jz = 0; jz < dz; jz++) {
      for (jy = 0; jy < dy; jy++) {
        for (jx = 0; jx < dx; jx++) {
          int j = ((((jz * dx) * dy) + (jy * dx)) + jx);
          buff[j] = jx * jy * jz + 10;
        }
      }
    }
}

static struct __PSStencil_kernel1 __PSStencilMap_kernel1(__PSDomain dom, PSGrid3DFloat g)
/* Generated by generateMap */
{
  struct __PSStencil_kernel1 stencil = {dom, g, __PSGridGetID(g)};
  return stencil;
}

static struct __PSStencil_kernel2 __PSStencilMap_kernel2(__PSDomain dom, PSGrid3DFloat g)
/* Generated by generateMap */
{
  struct __PSStencil_kernel2 stencil = {dom, g, __PSGridGetID(g)};
  return stencil;
}

static void __PSStencilRun_0(int iter, struct __PSStencil_kernel1 s0)
{
  int i;
  size_t localsize[PS_MAX_DIM] = {64, 4, 1};
  size_t globalsize[PS_MAX_DIM] = {
    (size_t)(ceil(s0.dom.local_max[0] / 64.0000) * 64),
    (size_t)(ceil(s0.dom.local_max[1] / 4.00000) * 4),
    1
  };
  __PSTraceStencilPre("kernel1");
  __PSStopwatch st;
  __PSStopwatchStart(&st);
  for (i = 0; i < iter; ++i) {
    int argc = 0;
    __PSSetKernel("__PSStencilRun_kernel1");
      { long int j = s0.dom.local_min[0]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_max[0]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_min[1]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_max[1]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_min[2]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_max[2]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = __PSGridDimDev(s0.g, 0); __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = __PSGridDimDev(s0.g, 1); __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = __PSGridDimDev(s0.g, 2); __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { void *buf = s0.g->buf; __PSSetKernelArgCLMem(argc, (void *)(&buf)); argc++; }
      { long int j = s0.g->gridattr; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
    __PSRunKernel(globalsize, localsize);
    __PSGridSwap(s0.g);
  }
  __PSTraceStencilPost(__PSStopwatchStop(&st));
}

static void __PSStencilRun_1(int iter, struct __PSStencil_kernel2 s0)
{
  int i;
  size_t localsize[PS_MAX_DIM] = {64, 4, 1};
  size_t globalsize[PS_MAX_DIM] = {
    (size_t)(ceil(s0.dom.local_max[0] / 64.0000) * 64),
    (size_t)(ceil(s0.dom.local_max[1] / 4.00000) * 4),
    1
  };
  __PSTraceStencilPre("kernel2");
  __PSStopwatch st;
  __PSStopwatchStart(&st);
  for (i = 0; i < iter; ++i) {
    int argc = 0;
    __PSSetKernel("__PSStencilRun_kernel2");
      { long int j = s0.dom.local_min[0]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_max[0]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_min[1]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_max[1]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_min[2]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = s0.dom.local_max[2]; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = __PSGridDimDev(s0.g, 0); __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = __PSGridDimDev(s0.g, 1); __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { long int j = __PSGridDimDev(s0.g, 2); __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
      { void *buf = s0.g->buf; __PSSetKernelArgCLMem(argc, (void *)(&buf)); argc++; }
      { long int j = s0.g->gridattr; __PSSetKernelArg(argc, sizeof(long int), &j); argc++; }
    __PSRunKernel(globalsize, localsize);
    __PSGridSwap(s0.g);
  }
  __PSTraceStencilPost(__PSStopwatchStop(&st));
}

int main(int argc, char **argv){
  PSInit(&argc, &argv, NDIM, SIZEX, SIZEY, SIZEZ);

  PSGrid3DFloat g1;
  {
    int dims[3] = {SIZEX, SIZEY, SIZEZ};
    g1 = __PSGridNew(sizeof(float), NDIM, dims, 0);
  }
  PSDomain3D d1 = PSDomain3DNew(0L, SIZEX, 0L, SIZEY, 0L, SIZEZ);

  int nx = SIZEX;
  int ny = SIZEY;
  int nz = SIZEZ;

  float *buff1 = (float *)(malloc((sizeof(float)) * nx * ny * nz));
  float *buff2 = (float *)(malloc((sizeof(float)) * nx * ny * nz));
  init(buff1, nx, ny, nz);

  PSGridCopyin(g1, buff1);
  PSGridCopyout(g1, buff2);

  size_t nelms = nx * ny * nz;
  unsigned int i;
  for (i = 0; i < nelms; i++) {
    if (buff1[i] == buff2[i]) continue;
    fprintf(stderr, "Error: buff 1 and 2 differ at %i: %10.3f and %10.3f\n", i, buff1[i], buff2[i]);
  }

  PSGridCopyin(g1, buff1);
  __PSStencilRun_0(1, __PSStencilMap_kernel1(d1, g1));
  PSGridCopyout(g1, buff2);
  for (i = 0; i < nelms; i++) {
    if (buff1[i] * 2 == buff2[i]) {
      continue;
    } else {
    fprintf(stderr, "Error: buff 1 and 2 differ at %i: %10.3f and %10.3f\n", i, buff1[i], buff2[i]);
    }
  }

  PSGridCopyin(g1, buff1);
  __PSStencilRun_1(1, __PSStencilMap_kernel2(d1, g1));
  PSGridCopyout(g1, buff2);
  for (i = 0; i < nelms; i++) {
    if (buff1[i] + 10 == buff2[i]) {
      continue;
    } else {
    fprintf(stderr, "Error: buff 1 and 2 differ at %i: %10.3f and %10.3f\n", i, buff1[i], buff2[i]);
    }
  }

  free(buff1);
  free(buff2);
  PSGridFree(g1);
  PSFinalize();
}

#endif /* PHYSIS_OPENCL_KERNEL_MODE */
