# ROSE_INCLUDE_DIR
# ROSE_LIBRARIES
# ROSE_FOUND = true if ROSE is found

FIND_PATH(ROSE_INCLUDE_DIR rose.h NO_SYSTEM_ENVIRONMENT_PATH)
FIND_LIBRARY(ROAE_LIBRARIES rose  NO_SYSTEM_ENVIRONMENT_PATH)
FIND_LIBRARY(ROSE_LIBRARIES rose)

SET(ROSE_FOUND FALSE)
IF(ROSE_INCLUDE_DIR AND ROSE_LIBRARIES)
MESSAGE(STATUS "ROSE_INCLUDE_DIR=${ROSE_INCLUDE_DIR}")
MESSAGE(STATUS "ROSE_LIBRARIES=${ROSE_LIBRARIES}")
SET(ROSE_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
ROSE_INCLUDE_DIR
ROSE_LIBRARIES
ROSE_FOUND
)
