# ROSE_INCLUDE_DIR
# ROSE_LIBRARIES
# ROSE_FOUND = true if ROSE is found

FIND_PATH(ROSE_INCLUDE_DIR rose.h PATH_SUFFIXES rose NO_SYSTEM_ENVIRONMENT_PATH)
FIND_LIBRARY(ROSE_LIBRARIES rose  NO_SYSTEM_ENVIRONMENT_PATH)
FIND_LIBRARY(ROSE_LIBRARIES rose)

SET(ROSE_FOUND FALSE)
IF(ROSE_INCLUDE_DIR AND ROSE_LIBRARIES)
MESSAGE(STATUS "ROSE_INCLUDE_DIR=${ROSE_INCLUDE_DIR}")
MESSAGE(STATUS "ROSE_LIBRARIES=${ROSE_LIBRARIES}")
SET(ROSE_FOUND TRUE)
string(REGEX MATCH "include/rose$" ROSE_EDG4X ${ROSE_INCLUDE_DIR})
if (ROSE_EDG4X)
  message(STATUS "Detected ROSE EDG4X")
  set(ROSE_EDG4X TRUE)
else ()
  message(STATUS "Detected ROSE EDG3")
endif ()
ENDIF()

MARK_AS_ADVANCED(
ROSE_INCLUDE_DIR
ROSE_LIBRARIES
ROSE_FOUND
)
