#ifndef PHYSIS_TRANSLATOR_COMMON_H_
#define PHYSIS_TRANSLATOR_COMMON_H_

#include "common/config.h"

#cmakedefine CUDA_TRANSLATOR_ENABLED
#cmakedefine MPI_TRANSLATOR_ENABLED
#cmakedefine MPI_OPENMP_TRANSLATOR_ENABLED
#cmakedefine MPI_CUDA_TRANSLATOR_ENABLED
#cmakedefine OPENCL_TRANSLATOR_ENABLED
#cmakedefine MPI_OPENCL_TRANSLATOR_ENABLED

#endif /* PHYSIS_COMMON_CONFIG_H_ */